### ISSUE TITLE
A second call to what cb2p() return does NOT match the first call!

### ISSUE THREAD

**Issue by Clarence-pan** [purplestone/cb2p#1]
This bug came out today in my project. I've simplified the scene into a qunit test: <https://github.com/Clarence-pan/cb2p/commit/1fdc388e9b83145d230dd32fdb246ae79b270c21>

The test result is like this: 
```
...
√  obj.method.p2cb.this:  [run1] this should equal obj
√  obj.method.p2cb.this:  [run1] should OK
√  obj.method.p2cb.this:  [run1] beforeCb should be called
×  obj.method.p2cb.this:  [run2] this should equal obj
√  obj.method.p2cb.this:  [run2] should OK
...
```

The `this` in the second call is not the same with what `this` is in the first call!

**Comment by Clarence-pan** [comment]
well, I have figured out why it happened. The `fn` was changed during the first call!
Thus I created a PR to resolve this issue: https://github.com/purplestone/cb2p/pull/2

**Comment by purplestone** [comment]
Thanks  your contributions
